// <auto-generated />
using System;
using BeeKeeperApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeeKeeperApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Apiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Paraje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeccionPolicial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrashumanciaHabilitada")
                        .HasColumnType("bit");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apiarios");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Colmena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiarioId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Poblacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioId");

                    b.ToTable("Colmenas");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Exportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadBarriles")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Exportaciones");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Extraccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CantidadKg")
                        .HasColumnType("float");

                    b.Property<int>("ColmenaId")
                        .HasColumnType("int");

                    b.Property<int?>("ExportacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ColmenaId");

                    b.HasIndex("ExportacionId");

                    b.ToTable("Extracciones");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Reina", b =>
                {
                    b.Property<int>("ColmenaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Presencia")
                        .HasColumnType("bit");

                    b.Property<string>("Salud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColmenaId");

                    b.ToTable("Reinas");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColmenaId")
                        .HasColumnType("int");

                    b.Property<string>("Dosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enfermedades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enjambrazon")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HayCrias")
                        .HasColumnType("bit");

                    b.Property<string>("NivelInfestacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plagas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoblacionEstimada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProximaDosis")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReinaPresente")
                        .HasColumnType("bit");

                    b.Property<string>("ReinaSalud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoTratamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sintomas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tratamiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColmenaId");

                    b.ToTable("Revisiones");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiarioId")
                        .HasColumnType("int");

                    b.Property<int?>("ColmenaId")
                        .HasColumnType("int");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioId");

                    b.HasIndex("ColmenaId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Trashumancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiarioDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("ApiarioOrigenId")
                        .HasColumnType("int");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioDestinoId");

                    b.HasIndex("ApiarioOrigenId");

                    b.ToTable("Trashumancias");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Colmena", b =>
                {
                    b.HasOne("BeeKeeperApp.Models.Entities.Apiario", "Apiario")
                        .WithMany("Colmenas")
                        .HasForeignKey("ApiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiario");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Extraccion", b =>
                {
                    b.HasOne("BeeKeeperApp.Models.Entities.Colmena", "Colmena")
                        .WithMany("Extracciones")
                        .HasForeignKey("ColmenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeeKeeperApp.Models.Entities.Exportacion", "Exportacion")
                        .WithMany("Extracciones")
                        .HasForeignKey("ExportacionId");

                    b.Navigation("Colmena");

                    b.Navigation("Exportacion");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Reina", b =>
                {
                    b.HasOne("BeeKeeperApp.Models.Entities.Colmena", "Colmena")
                        .WithOne("Reina")
                        .HasForeignKey("BeeKeeperApp.Models.Entities.Reina", "ColmenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmena");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Revision", b =>
                {
                    b.HasOne("BeeKeeperApp.Models.Entities.Colmena", "Colmena")
                        .WithMany("Revisiones")
                        .HasForeignKey("ColmenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BeeKeeperApp.Models.Entities.Clima", "CondicionesClimaticas", b1 =>
                        {
                            b1.Property<int>("RevisionId")
                                .HasColumnType("int");

                            b1.Property<string>("DireccionViento")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DireccionViento");

                            b1.Property<double?>("Humedad")
                                .HasColumnType("float")
                                .HasColumnName("Humedad");

                            b1.Property<double?>("Presion")
                                .HasColumnType("float")
                                .HasColumnName("Presion");

                            b1.Property<double?>("Temperatura")
                                .HasColumnType("float")
                                .HasColumnName("Temperatura");

                            b1.Property<double?>("VelocidadViento")
                                .HasColumnType("float")
                                .HasColumnName("VelocidadViento");

                            b1.HasKey("RevisionId");

                            b1.ToTable("Clima", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RevisionId");
                        });

                    b.Navigation("Colmena");

                    b.Navigation("CondicionesClimaticas");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Tarea", b =>
                {
                    b.HasOne("BeeKeeperApp.Models.Entities.Apiario", "Apiario")
                        .WithMany()
                        .HasForeignKey("ApiarioId");

                    b.HasOne("BeeKeeperApp.Models.Entities.Colmena", "Colmena")
                        .WithMany("Tareas")
                        .HasForeignKey("ColmenaId");

                    b.Navigation("Apiario");

                    b.Navigation("Colmena");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Trashumancia", b =>
                {
                    b.HasOne("BeeKeeperApp.Models.Entities.Apiario", "ApiarioDestino")
                        .WithMany()
                        .HasForeignKey("ApiarioDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeeKeeperApp.Models.Entities.Apiario", "ApiarioOrigen")
                        .WithMany()
                        .HasForeignKey("ApiarioOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiarioDestino");

                    b.Navigation("ApiarioOrigen");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Apiario", b =>
                {
                    b.Navigation("Colmenas");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Colmena", b =>
                {
                    b.Navigation("Extracciones");

                    b.Navigation("Reina");

                    b.Navigation("Revisiones");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("BeeKeeperApp.Models.Entities.Exportacion", b =>
                {
                    b.Navigation("Extracciones");
                });
#pragma warning restore 612, 618
        }
    }
}
